name: Update data

defaults:
  run:
    shell: /usr/bin/bash {0}

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 10,15,21,0 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout Data objects and setup
        run: |
          git clone https://github.com/kiss-oliver/106.git
          cd 106
          git lfs checkout
          pip3 install pandas
          pip3 install altair
          pip3 install altair_saver
          pip3 install unidecode
          pip3 install tqdm
      - name: Generate graphs
        run: |
          cd generators
          python3 generate_sum_chart.py
          python3 generate_county_charts.py
          python3 generate_szk_charts.py
          cd ../_includes
          git config --global user.name 'Automated workflow - Update data'
          git config --global user.email 'kiss-oliver@users.noreply.github.com'
          git add SumFigures/*.json
          git add OEVKfigures/*.json
          git add SZKfigures/*.json
          git commit -m "Update main summary charts using update data workflow."
          git push
